WIP

diff --git a/.config/lf/lfrc b/.config/lf/lfrc
--- a/.config/lf/lfrc
+++ b/.config/lf/lfrc
@@ -134,6 +134,26 @@ cmd split_to_nvim ${{
   fi
 }}
 
+cmd cd_sync ${{
+  if [ ! -f "$HOME/.tmux-pane-id" ]; then
+    return 0
+   fi
+  # get the last pane index
+  last_pane=$(tail -n 2 ~/.tmux-pane-id | head -n 1)
+  if [ -z "$last_pane" ]; then
+    echo "last_pane not found"
+    return 0
+  fi
+  pane_pid=$(tmux list-panes -a -F '#{pane_index} #{pane_pid}' | grep "$last_pane " | cut -d ' ' -f2 )
+  if [ -z "$pane_pid" ]; then
+    echo "pane_pid not found"
+    return 0
+  fi
+  if ! $(pstree -p "$pane_pid" | grep -qE 'zsh\(.*\)$'); then
+    tmux send-keys -t "$last_pane" "cd $PWD" C-m
+  fi
+}}
+
 
 # vim quit
 cmd q :quit
